In [1]:
import sys
print(sys.executable)

c:\Users\alana\Documents\financial-services-complaints-project\.venv\Scripts\python.exe

In [2]:
import pandas as pd

In [3]:
complaints = pd.read_csv("../data/complaints.csv")

In [4]:
complaints.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-03-11T14:35:15.000Z,Mortgage,Other type of mortgage,Struggling to pay mortgage,NaN,Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,FL,33541,NaN,Web,2023-03-11T14:42:35.000Z,Closed with explanation,Yes,6681446
1,2023-03-11T15:25:45.000Z,Mortgage,FHA mortgage,Trouble during payment process,NaN,Company believes complaint represents an oppor...,Mr. Cooper Group Inc.,MI,494XX,Servicemember,Web,2023-03-11T16:06:56.000Z,Closed with explanation,Yes,6681226
2,2023-03-11T15:59:06.000Z,Mortgage,FHA mortgage,Trouble during payment process,NaN,NaN,"EQUITY RESOURCES, INCORPORATED",OH,456XX,NaN,Web,2023-03-11T16:29:11.000Z,Closed with explanation,Yes,6681308
3,2023-03-11T16:35:15.000Z,Mortgage,FHA mortgage,Trouble during payment process,NaN,NaN,Mr. Cooper Group Inc.,NY,11580,NaN,Web,2023-03-11T16:55:49.000Z,Closed with explanation,Yes,6681193
4,2023-03-11T16:39:57.000Z,Mortgage,Conventional home mortgage,Trouble during payment process,NaN,Company has responded to the consumer and the ...,Specialized Loan Servicing Holdings LLC,VA,24127,Servicemember,Web,2023-03-11T17:23:24.000Z,Closed with explanation,Yes,6681137

In [5]:
complaints.shape

(98933, 15)

In [7]:
complaints.info()

<class 'pandas.DataFrame'>
RangeIndex: 98933 entries, 0 to 98932
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date received                 98933 non-null  str
 1   Product                       98933 non-null  str
 2   Sub-product                   98933 non-null  str
 3   Issue                         98933 non-null  str
 4   Sub-issue                     79170 non-null  str
 5   Company public response       46415 non-null  str
 6   Company                       98933 non-null  str
 7   State                         98692 non-null  str
 8   ZIP code                      98890 non-null  str
 9   Tags                          28341 non-null  str
 10  Submitted via                 98933 non-null  str
 11  Date sent to company          98933 non-null  str
 12  Company response to consumer  98932 non-null  str
 13  Timely response?              98933 non-null  str
 14  Complaint ID                  98933 non-null  int64
dtypes: int64(1), str(14)
memory usage: 11.3 MB

In [9]:
complaints['Complaint ID'].nunique()

98933

In [10]:
complaints['Complaint ID'].duplicated().sum()

np.int64(0)

In [11]:
complaints.isna().sum().sort_values(ascending=False)

Tags                            70592
Company public response         52518
Sub-issue                       19763
State                             241
ZIP code                           43
Company response to consumer        1
Date received                       0
Company                             0
Issue                               0
Product                             0
Sub-product                         0
Submitted via                       0
Date sent to company                0
Timely response?                    0
Complaint ID                        0
dtype: int64

In [14]:
(
    complaints.isna()
    .mean()
    .mul(100)
    .round(1)
    .sort_values(ascending=False)
)

Tags                            71.4
Company public response         53.1
Sub-issue                       20.0
State                            0.2
Product                          0.0
Sub-product                      0.0
Date received                    0.0
Company                          0.0
Issue                            0.0
ZIP code                         0.0
Submitted via                    0.0
Date sent to company             0.0
Company response to consumer     0.0
Timely response?                 0.0
Complaint ID                     0.0
dtype: float64

In [15]:
complaints['Complaint ID'].nunique()

98933

In [16]:
complaints['Complaint ID'].duplicated().sum()

np.int64(0)

In [17]:
complaints.isna().sum().sort_values(ascending=False)

Tags                            70592
Company public response         52518
Sub-issue                       19763
State                             241
ZIP code                           43
Company response to consumer        1
Date received                       0
Company                             0
Issue                               0
Product                             0
Sub-product                         0
Submitted via                       0
Date sent to company                0
Timely response?                    0
Complaint ID                        0
dtype: int64

In [18]:
complaints['Date received'] = pd.to_datetime(complaints['Date received'],errors='coerce')
complaints['Date sent to company'] = pd.to_datetime(complaints['Date sent to company'],errors='coerce')

In [20]:
complaints[['Date received', 'Date sent to company']].isna().sum()

Date received           0
Date sent to company    0
dtype: int64

In [21]:
complaints[['Date received', 'Date sent to company']].dtypes

Date received           datetime64[us, UTC]
Date sent to company    datetime64[us, UTC]
dtype: object

In [22]:
complaints['Product'].value_counts().head(10)

Product
Mortgage    98933
Name: count, dtype: int64

In [23]:
complaints['Issue'].value_counts().head(10)

Issue
Trouble during payment process                                                      50644
Struggling to pay mortgage                                                          25724
Applying for a mortgage or refinancing an existing mortgage                         10292
Closing on a mortgage                                                                7473
Incorrect information on your report                                                 2773
Problem with a company's investigation into an existing problem                      1275
Improper use of your report                                                           372
Problem with a credit reporting company's investigation into an existing problem      146
Credit monitoring or identity theft protection services                               124
Unable to get your credit report or credit score                                       66
Name: count, dtype: int64

In [24]:
complaints['Company'].value_counts().head(10)

Company
Shellpoint Partners, LLC             10072
WELLS FARGO & COMPANY                 7509
Mr. Cooper Group Inc.                 6871
Ocwen Financial Corporation           4463
Rocket Mortgage, LLC                  4404
Freedom Mortgage Company              4324
SELECT PORTFOLIO SERVICING, INC.      3765
PENNYMAC LOAN SERVICES, LLC.          2449
CARRINGTON MORTGAGE SERVICES, LLC     2379
Selene Holdings LLC                   2253
Name: count, dtype: int64

In [26]:
(
    complaints['Issue']
    .value_counts(normalize=True)
    .mul(100)
    .round(1)
    .head(10)

)

Issue
Trouble during payment process                                                      51.2
Struggling to pay mortgage                                                          26.0
Applying for a mortgage or refinancing an existing mortgage                         10.4
Closing on a mortgage                                                                7.6
Incorrect information on your report                                                 2.8
Problem with a company's investigation into an existing problem                      1.3
Improper use of your report                                                          0.4
Problem with a credit reporting company's investigation into an existing problem     0.1
Credit monitoring or identity theft protection services                              0.1
Unable to get your credit report or credit score                                     0.1
Name: proportion, dtype: float64

In [27]:
(
    complaints['Company']
    .value_counts(normalize=True)
    .mul(100)
    .round(1)
    .head(10)
)

Company
Shellpoint Partners, LLC             10.2
WELLS FARGO & COMPANY                 7.6
Mr. Cooper Group Inc.                 6.9
Ocwen Financial Corporation           4.5
Rocket Mortgage, LLC                  4.5
Freedom Mortgage Company              4.4
SELECT PORTFOLIO SERVICING, INC.      3.8
PENNYMAC LOAN SERVICES, LLC.          2.5
CARRINGTON MORTGAGE SERVICES, LLC     2.4
Selene Holdings LLC                   2.3
Name: proportion, dtype: float64

In [28]:
complaints['Date received'].min()

Timestamp('2022-10-01 00:06:38+0000', tz='UTC')

In [29]:
complaints['Date received'].max()

Timestamp('2026-09-30 16:08:27+0000', tz='UTC')

In [31]:
monthly_complaints = (
    complaints
    .groupby(pd.Grouper(key='Date received', freq='MS'))
    .size()
    .reset_index(name='complaint_count')

)

In [32]:
monthly_complaints.head()

              Date received  complaint_count
0 2022-10-01 00:00:00+00:00             1624
1 2022-11-01 00:00:00+00:00             1518
2 2022-12-01 00:00:00+00:00             1824
3 2023-01-01 00:00:00+00:00             2837
4 2023-02-01 00:00:00+00:00             2165